// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjbJvjKFN24-3Q8dgk9NJMYM2Dh1yGBk',
    appId: '1:746891501661:web:a86a7fa652dc3ce9e4adb4',
    messagingSenderId: '746891501661',
    projectId: 'foodapp-47e5a',
    authDomain: 'foodapp-47e5a.firebaseapp.com',
    storageBucket: 'foodapp-47e5a.appspot.com',
    measurementId: 'G-G77LDESF62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmFfq34EvfVp-_cbSXwsd0LB56p-U2G38',
    appId: '1:746891501661:android:fe5702ba9128b7d7e4adb4',
    messagingSenderId: '746891501661',
    projectId: 'foodapp-47e5a',
    storageBucket: 'foodapp-47e5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbHKhRN57DcidVX8nOg6SP10QYJuwG-No',
    appId: '1:746891501661:ios:209552c061c0ac69e4adb4',
    messagingSenderId: '746891501661',
    projectId: 'foodapp-47e5a',
    storageBucket: 'foodapp-47e5a.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbHKhRN57DcidVX8nOg6SP10QYJuwG-No',
    appId: '1:746891501661:ios:b4b09d4c531c6787e4adb4',
    messagingSenderId: '746891501661',
    projectId: 'foodapp-47e5a',
    storageBucket: 'foodapp-47e5a.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
